### ISSUE TITLE
Tomb Raider 2 crash and loss of save data

### ISSUE THREAD

**Issue by EQQx110** [Rinnegatamante/raider-vita#8] opened 2022-09-03 02:47 UTC
I’ve encountered a bug in which, after I load any save file a few times (around 7 times), the last time I try to load, it doesn’t complete the loading and the game crashes and takes me back to the home screen. When I get back in the game, the last save file made in the session where it crashed is replaced by an older save file (it seems even with save files that were overwritten and so apparently deleted), and it seems to be lost (maybe it’s still somewhere not accessible trough the game).
The error that I get when the game crashes is the following:
”An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded.
ux0:data/psp2core-1662172676-0x00020f369f-game.bin.psp2dmp”
If you need any other info, I’ll be happy to help.
Sorry for bad english.

Edit: I forgot to add that it isn’t occasional, it happens in every session, thus making the game almost unplayable (I need to always save twice, I have lesser slots to save, after I load around 7 times I have to reopen the game, it’s too annoying.)

**Comment by Rinnegatamante** [comment] 2022-09-04 12:55
Duplicate of: https://github.com/Rinnegatamante/raider-vita/issues/3

**Closed by Rinnegatamante** 2022-09-04 12:55 UTC

**Comment by BoKKeR** [comment] 2025-03-17 17:35
The save file being rewritten really breaks the usability :(
